### ISSUE TITLE
`@storybook/addons` issues with Storybook 8 support

### ISSUE THREAD

**Issue by JamyGolden** [bitttttten/storybook-mock-date-decorator#5]
Hello @bitttttten, I see https://github.com/bitttttten/storybook-mock-date-decorator/pull/4 fixed some issues, but there are new issues with the release of Storybook 8: It doesn't use `@storybook/addons` anymore and is contents have been moved to `@storybook/preview-api`. https://www.npmjs.com/package/@storybook/addons

**Comment by bitttttten** [comment]
Hi @JamyGolden !

I actually have stopped using Storybook and have stopped maintaining this package. So I won't be doing any more maintenance on it 🥲 

You are welcome to submit a PR or fork the repo to continue the work on, otherwise I won't actively be doing any work to support Storybook 8. I understand it's not the answer you wanted, and hope you understand :)

**Comment by JamyGolden** [comment]
I maintain several repos and totally understand :smile:  I ended up copying your code and just pasted it in a decorator function and did some small changes and it worked. I thought about submitting a PR but it adds the complication of not supporting storybook < 8 with the update, so I didn't create a PR.

Thanks for the quick response!

**Comment by ilovett** [comment]
@JamyGolden could you please share your snippet with preview api

**Comment by bitttttten** [comment]
@JamyGolden this should now be supported in v2.0.1 🫡

**Comment by JamyGolden** [comment]
Great, thank you! :pray:
